name: Code Quality Checks

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  code-quality:
    uses: wp-cli/.github/.github/workflows/reusable-code-quality.yml@b74ae572642939532600b2980f0be693e5ba4219
